
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelineversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelineversions/finalizers
  verbs:
  - update
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - pipelineversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - recurringruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - recurringruns/finalizers
  verbs:
  - update
- apiGroups:
  - kfp.jackhoman.com
  resources:
  - recurringruns/status
  verbs:
  - get
  - patch
  - update
