// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/johnhoman/kfp-releaser/pkg/kfp/http/models"
)

// NewCreatePipelineVersionParams creates a new CreatePipelineVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePipelineVersionParams() *CreatePipelineVersionParams {
	return &CreatePipelineVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePipelineVersionParamsWithTimeout creates a new CreatePipelineVersionParams object
// with the ability to set a timeout on a request.
func NewCreatePipelineVersionParamsWithTimeout(timeout time.Duration) *CreatePipelineVersionParams {
	return &CreatePipelineVersionParams{
		timeout: timeout,
	}
}

// NewCreatePipelineVersionParamsWithContext creates a new CreatePipelineVersionParams object
// with the ability to set a context for a request.
func NewCreatePipelineVersionParamsWithContext(ctx context.Context) *CreatePipelineVersionParams {
	return &CreatePipelineVersionParams{
		Context: ctx,
	}
}

// NewCreatePipelineVersionParamsWithHTTPClient creates a new CreatePipelineVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePipelineVersionParamsWithHTTPClient(client *http.Client) *CreatePipelineVersionParams {
	return &CreatePipelineVersionParams{
		HTTPClient: client,
	}
}

/* CreatePipelineVersionParams contains all the parameters to send to the API endpoint
   for the create pipeline version operation.

   Typically these are written to a http.Request.
*/
type CreatePipelineVersionParams struct {

	/* Body.

	     ResourceReference inside PipelineVersion specifies the pipeline that this
	version belongs to.
	*/
	Body *models.APIPipelineVersion

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create pipeline version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePipelineVersionParams) WithDefaults() *CreatePipelineVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create pipeline version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePipelineVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create pipeline version params
func (o *CreatePipelineVersionParams) WithTimeout(timeout time.Duration) *CreatePipelineVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create pipeline version params
func (o *CreatePipelineVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create pipeline version params
func (o *CreatePipelineVersionParams) WithContext(ctx context.Context) *CreatePipelineVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create pipeline version params
func (o *CreatePipelineVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create pipeline version params
func (o *CreatePipelineVersionParams) WithHTTPClient(client *http.Client) *CreatePipelineVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create pipeline version params
func (o *CreatePipelineVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create pipeline version params
func (o *CreatePipelineVersionParams) WithBody(body *models.APIPipelineVersion) *CreatePipelineVersionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create pipeline version params
func (o *CreatePipelineVersionParams) SetBody(body *models.APIPipelineVersion) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePipelineVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
