// Code generated by go-swagger; DO NOT EDIT.

package pipeline_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPipelineVersionParams creates a new GetPipelineVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPipelineVersionParams() *GetPipelineVersionParams {
	return &GetPipelineVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPipelineVersionParamsWithTimeout creates a new GetPipelineVersionParams object
// with the ability to set a timeout on a request.
func NewGetPipelineVersionParamsWithTimeout(timeout time.Duration) *GetPipelineVersionParams {
	return &GetPipelineVersionParams{
		timeout: timeout,
	}
}

// NewGetPipelineVersionParamsWithContext creates a new GetPipelineVersionParams object
// with the ability to set a context for a request.
func NewGetPipelineVersionParamsWithContext(ctx context.Context) *GetPipelineVersionParams {
	return &GetPipelineVersionParams{
		Context: ctx,
	}
}

// NewGetPipelineVersionParamsWithHTTPClient creates a new GetPipelineVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPipelineVersionParamsWithHTTPClient(client *http.Client) *GetPipelineVersionParams {
	return &GetPipelineVersionParams{
		HTTPClient: client,
	}
}

/* GetPipelineVersionParams contains all the parameters to send to the API endpoint
   for the get pipeline version operation.

   Typically these are written to a http.Request.
*/
type GetPipelineVersionParams struct {

	/* VersionID.

	   The ID of the pipeline version to be retrieved.
	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pipeline version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPipelineVersionParams) WithDefaults() *GetPipelineVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pipeline version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPipelineVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pipeline version params
func (o *GetPipelineVersionParams) WithTimeout(timeout time.Duration) *GetPipelineVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pipeline version params
func (o *GetPipelineVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pipeline version params
func (o *GetPipelineVersionParams) WithContext(ctx context.Context) *GetPipelineVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pipeline version params
func (o *GetPipelineVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pipeline version params
func (o *GetPipelineVersionParams) WithHTTPClient(client *http.Client) *GetPipelineVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pipeline version params
func (o *GetPipelineVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersionID adds the versionID to the get pipeline version params
func (o *GetPipelineVersionParams) WithVersionID(versionID string) *GetPipelineVersionParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get pipeline version params
func (o *GetPipelineVersionParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPipelineVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version_id
	if err := r.SetPathParam("version_id", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
